%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Calibrate model to individual country data
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
filename = sprintf('../Drafts/table_jv_individual.txt');
f = fopen(filename,'w');

% Set initial parameters and options for minsearch
initial = [Setup{'Formal','Epsilon'}, Setup{'Informal','Epsilon'}];
options = optimset('MaxFunEvals',5000); % allow for enough iterations

% Set initial row counter
n = 1;

% Baseline
count = 41;
Alt = Setup;
name = 'Baseline';
mcrobusti(Alt,time,T,name,f,count,n);
n = n + 1;

% Sample changes
fprintf(f,' \\\\ \n');
fprintf(f,'\\multicolumn{7}{c}{\\textit{Individual Calibrations:}} \\\\ \n');

% Run the script written by Stata that calibrates for each country
% As part of these calls, the values of elasticities are accumulated in a
% matrix called 'Eps'
run('../Work/jvextract_individual');

% Run with median and mean
Setup.Size = [.0445; .0445; .911]; % reset to mean urbanization initial conditions

fitted = median(Eps); % use median of the accumulated elasticities
R = mcfix(time,fitted,Setup);
Alt = Setup; 
Alt.PostCDR = Alt.PreCDR; % alt has no difference in pre/post CDR
S = mcfix(time,fitted,Alt); % solve the model without UMT
fprintf(f,'%9.0f. %s & %9.0f & %9.1f & %9.1f & %9.2f & %9.3f & %9.3f \\\\ \n', ...
        n, ...
        'Median elasticities', ...
        1, ...
        100*S{time,'UrbPerc'} - 100*R{time,'UrbPerc'}, ...
        100*S{time,'InfUrbPerc'} - 100*R{time,'InfUrbPerc'}, ...
        S{time,'Welfare'}/R{time,'Welfare'}, ...
        fitted(1), fitted(2));

n = n+1;
fitted = mean(Eps);
R = mcfix(time,fitted,Setup);
Alt = Setup; 
Alt.PostCDR = Alt.PreCDR; % alt has no difference in pre/post CDR
S = mcfix(time,fitted,Alt); % solve the model without UMT
fprintf(f,'%9.0f. %s & %9.0f & %9.1f & %9.1f & %9.2f & %9.3f & %9.3f \\\\ \n', ...
        n, ...
        'Mean elasticities', ...
        1, ...
        100*S{time,'UrbPerc'} - 100*R{time,'UrbPerc'}, ...
        100*S{time,'InfUrbPerc'} - 100*R{time,'InfUrbPerc'}, ...
        S{time,'Welfare'}/R{time,'Welfare'}, ...
        fitted(1), fitted(2));

n = n + 1;
Esort = sortrows(Eps,1);  % sort by formal   
fitted = mean(Esort(1:30,:)); % only the 30 lowest formal elasticities
R = mcfix(time,fitted,Setup);
Alt = Setup; 
Alt.PostCDR = Alt.PreCDR; % alt has no difference in pre/post CDR
S = mcfix(time,fitted,Alt); % solve the model without UMT
fprintf(f,'%9.0f. %s & %9.0f & %9.1f & %9.1f & %9.2f & %9.3f & %9.3f \\\\ \n', ...
        n, ...
        'Lowest 30 Formal', ...
        1, ...
        100*S{time,'UrbPerc'} - 100*R{time,'UrbPerc'}, ...
        100*S{time,'InfUrbPerc'} - 100*R{time,'InfUrbPerc'}, ...
        S{time,'Welfare'}/R{time,'Welfare'}, ...
        fitted(1), fitted(2));

n = n + 1;    
Esort = sortrows(Eps,1);  % sort by formal   
fitted = mean(Esort(11:40,:)); % only the 30 highest formal elasticities
R = mcfix(time,fitted,Setup);
Alt = Setup; 
Alt.PostCDR = Alt.PreCDR; % alt has no difference in pre/post CDR
S = mcfix(time,fitted,Alt); % solve the model without UMT
fprintf(f,'%9.0f. %s & %9.0f & %9.1f & %9.1f & %9.2f & %9.3f & %9.3f \\\\ \n', ...
        n, ...
        'Highest 30 Formal', ...
        1, ...
        100*S{time,'UrbPerc'} - 100*R{time,'UrbPerc'}, ...
        100*S{time,'InfUrbPerc'} - 100*R{time,'InfUrbPerc'}, ...
        S{time,'Welfare'}/R{time,'Welfare'}, ...
        fitted(1), fitted(2));

n = n + 1;    
Esort = sortrows(Eps,2);  % sort by informal   
fitted = mean(Esort(1:30,:)); % only the 30 lowest informal elasticities
R = mcfix(time,fitted,Setup);
Alt = Setup; 
Alt.PostCDR = Alt.PreCDR; % alt has no difference in pre/post CDR
S = mcfix(time,fitted,Alt); % solve the model without UMT
fprintf(f,'%9.0f. %s & %9.0f & %9.1f & %9.1f & %9.2f & %9.3f & %9.3f \\\\ \n', ...
        n, ...
        'Lowest 30 Informal', ...
        1, ...
        100*S{time,'UrbPerc'} - 100*R{time,'UrbPerc'}, ...
        100*S{time,'InfUrbPerc'} - 100*R{time,'InfUrbPerc'}, ...
        S{time,'Welfare'}/R{time,'Welfare'}, ...
        fitted(1), fitted(2));    

n = n + 1;    
Esort = sortrows(Eps,2);  % sort by informal   
fitted = mean(Esort(11:40,:)); % only the 30 highest informal elasticities
R = mcfix(time,fitted,Setup);
Alt = Setup; 
Alt.PostCDR = Alt.PreCDR; % alt has no difference in pre/post CDR
S = mcfix(time,fitted,Alt); % solve the model without UMT
fprintf(f,'%9.0f. %s & %9.0f & %9.1f & %9.1f & %9.2f & %9.3f & %9.3f \\\\ \n', ...
        n, ...
        'Highest 30 Informal', ...
        1, ...
        100*S{time,'UrbPerc'} - 100*R{time,'UrbPerc'}, ...
        100*S{time,'InfUrbPerc'} - 100*R{time,'InfUrbPerc'}, ...
        S{time,'Welfare'}/R{time,'Welfare'}, ...
        fitted(1), fitted(2));    
    
fclose(f);   