%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Run model with given elasticities, compare with and w/o UMT
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function mcrobustk(Setup,time,fitted,name,f,n)
    R = mcfix(time,fitted,Setup); % solve the model with the fitted values
    
    fprintf(f,'%9.0f. %s & %9.1f & %9.1f & 1.0 & %9.1f & %9.1f & %9.1f & %9.1f & %9.1f & %9.1f \\\\ \n', ...
        n, ...
        name, ...
        100*(Setup{'Formal','Size'} + Setup{'Informal','Size'})/sum(Setup{:,'Size'}), ...
        100*(Setup{'Informal','Size'}/(Setup{'Formal','Size'} + Setup{'Informal','Size'})), ...
        100*R{100,'UrbPerc'},100*R{100,'InfUrbPerc'},R{100,'RelUrbSize'}, ...
        100*R{150,'UrbPerc'},100*R{150,'InfUrbPerc'},R{150,'RelUrbSize'});
end